fullnameOverride: legal-ai

image:
  repository: datapactacr.azurecr.io/legal
  tag: "v1.1.1"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-credentials

ingress:
  enabled: true
  className: traefik
  host: legalai.dp.assistcloud.net
  tls: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

replicaCount: 1

service:
  port: 8001
  targetPort: 8001
  type: ClusterIP

livenessProbe:
  httpGet:
    path: /
    port: 8001
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /
    port: 8001
  initialDelaySeconds: 60
  periodSeconds: 30

env:
  KEYCLOAK_ISSUER: "https://auth.dp.assistcloud.net/realms/datapact-ui-toolkit"
  KEYCLOAK_CLIENT_ID: "legal-ai"
